config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  resources :users
  resources :books do
    post 'borrow'
  end
  root to: 'main#index'
  get '/login', to: 'users#log_in', as: :log_in
  post '/sign_in', to: 'users#sign_in', as: :sign_in
  delete '/logout/:user_id', to: 'users#log_out', as: 'log_out'
  post '/return_book', to: 'main#return_book', as: :return_book
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_borrows
  validates :title, :author, :isbn, :genre, presence: true

  class << self
    def borrowed
      where.associated(:book_borrows).distinct
    end
  end
end

app/models/book_borrow.rb
class BookBorrow < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :book, uniqueness: { scope: :user }
  scope :overdue, -> { where('due_date < ?', Time.current) }
  scope :due_today, -> { where(due_date: Time.current.midnight..(Time.current.midnight + 1.day)) }
end

app/models/librarian.rb
class Librarian < User
  self.inheritance_column = 'role'

  before_create do
    self.role = :Librarian
  end

  def return_book!(member, book)
    BookBorrow.find_by(user: member, book: book).destroy

    book.update(quantity: book.quantity + 1)
  end
end

app/models/member.rb
class Member < User
  self.inheritance_column = 'role'

  before_create do
    self.role = :Member
  end

  def borrow!(book)
    return unless book.quantity.positive?

    ActiveRecord::Base.transaction do
      book.update!(quantity: book.quantity - 1)
      BookBorrow.create!(book: book, user: self, due_date: 12.days.from_now)
    end
  end

  def borrowed_books
    Book.joins(:book_borrows).where(book_borrows: { user: self })
  end

  def can_borrow?(book)
    !borrowed_books.where(id: book.id).any?
  end
end
  

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :book_borrows
  has_many :books, through: :book_borrows
  enum role: %i[Librarian Member]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :validate_user, only: %i[ update destroy create ]
  before_action :set_member, only: %i[ borrow ]

  # GET /books or /books.json
  def index
    if params[:search].present?
      @books = Book.where("title LIKE ?", "%#{Book.sanitize_sql_like(params[:search])}%")
                   .or(Book.where("author LIKE ?", "%#{Book.sanitize_sql_like(params[:search])}%"))
                   .or(Book.where("genre LIKE ?", "%#{Book.sanitize_sql_like(params[:search])}%"))
                   .or(Book.where("isbn LIKE ?", "%#{Book.sanitize_sql_like(params[:search])}%"))
                   .page(params[:page])

    else
      @books = Book.order(created_at: :desc).page(params[:page])
    end
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def borrow
    @book = Book.find(params[:book_id])

    if @member.can_borrow?(@book)
      @member.borrow!(@book)
    else
      flash[:alert] = 'Can not borrow this book again!'
    end
    redirect_to books_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_member
      if current_user.Member?
        @member = Member.find(current_user.id)
      else
        flash[:alert] = "Only members can borrow books!"
        redirect_back fallback_location: root_path
      end
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :genre, :isbn, :quantity)
    end

    def validate_user
      unless current_user && current_user.Librarian?
        flash[:alert] = 'Only librarians can perform that action!'
        redirect_back fallback_location: root_path
      end
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :set_member_or_librarian

  def index
    @books = Book.order(created_at: :desc).page(params[:page])
    @due_today = BookBorrow.due_today
  end

  def return_book
    @member = Member.find(params[:user_id])
    @book = Book.find(params[:book_id])
    @librarian.return_book!(@member, @book)
    redirect_to root_path
  end

  private
    def set_member_or_librarian
      return unless current_user

      if current_user.Librarian?
        @librarian = Librarian.find(current_user.id)
      else
        @member = Member.find(current_user.id)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def log_in
    @user = User.new
  end

  def sign_in
    @user = User.find_by(username: session_params[:username])

    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Error logging in"
      redirect_to log_in_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User created successfully"
      redirect_to root_path, status: :created
    else
      flash[:alert] = "Error creating user!"
      render :new, status: :unprocessable_entity
    end
  end

  def log_out
    session[:user_id] = nil
    redirect_to root_path
  end
  
  private

  def user_params
    params.require(:user).permit(:role, :username, :email, :password, :password_confirmation)
  end

  def session_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class='border border-gray-300 rounded-lg p-4 book-container' id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= book.genre %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= book.isbn %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= book.quantity %>
  </p>
  <% if current_user&.Member? %>
    <%= button_to "Borrow this book", book_borrow_path(book) %>
  <% end %>
  <%= link_to "Show this book", book, class: 'text-blue-600' %>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.text_field :genre %>
  </div>

  <div>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <span class="underline text-3xl p-3"><%= link_to "Book Catalog", books_path %></span>
  <%= link_to "New book", new_book_path, class: 'text-xl text-blue-600' %>
  <div id="books">

  <%= form_with url: books_path, method: :get do |f| %>
    <%= f.text_field :search %>
    <%= f.submit :search%>
  <% end %>

  <% @books.each do |book| %>
      <%= render book %>
    <% end %>
  </div>
  <%= paginate @books %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <h2 class='text-4xl font-extrabold m-5'><%= link_to 'Library Dashboard', root_path %></h2>
    <%= yield %>
  </body>
</html>

app/views/main/_books.html.erb
<div>
  <span class="underline text-3xl p-3">Book Catalog</span>
  <div id="books">
    <%= form_with url: books_path, method: :get do |f| %>
      <%= f.text_field :search %>
      <%= f.submit :search%>
    <% end %>
    <% @books.each do |book| %>
      <%= render book %>
    <% end %>
  </div>
  <%= paginate @books %>
</div>

app/views/main/_librarian_overview.html.erb
<div>
  <span> Due today </span>
  <% @due_today.each do |borrow| %>
    <%= render borrow.user %>
    <%= render borrow.book %>
    <%= button_to 'Mark as returned', return_book_path({user_id: borrow.user.id, book_id: borrow.book.id}) %>
  <% end %>
</div>

<div>
  <span> Overdue </span>
  <% BookBorrow.overdue.each do |borrow| %>
    <%= render borrow.user %>
    <%= render borrow.book %>
    <%= button_to 'Mark as returned', return_book_path({user_id: borrow.user.id, book_id: borrow.book.id}) %>
  <% end %>
</div>

app/views/main/index.html.erb
<div class='flex justify-between'>
  <% if current_user %>
    <span class='p-3 m-3 rounded-lg border-2 border-green-700'> Welcome back, <%=current_user.username%>!
    <%= link_to 'Log out', log_out_path(current_user), data: { "turbo-method": :delete }, class: 'text-blue-600' %>
    </span>
  <% else %> 
    <span>
      <%= link_to 'Become a member today', new_user_path, class: 'text-blue-600' %>
      or 
      <%= link_to 'Log in', log_in_path, class: 'text-blue-600' %>
    </span>
  <% end %>
</div>

<% if current_user %>
  <%= render partial: 'librarian_overview' if current_user.Librarian? %>
  <%= render partial: 'member_overview' if current_user.Member? %>
<% end %>

app/views/users/_user.html.erb
<div class='border border-blue-300 rounded-lg' id="<%= dom_id user %>">
  <p>
    <strong>Title:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= user.email %>
  </p>
</div>

app/views/users/log_in.html.erb
<h1>Member access</h1>

<%= form_with model: @user, url: sign_in_path do |f| %>
  <div>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <p>
    <%= f.submit 'Login' %>
  </p>
<% end %>

app/views/users/new.html.erb
<%= form_with model: @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :role %><br>
    <%= f.select :role, User.roles.keys %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>